export const QUERY_USER_INFO = 'QUERY_USER_INFO';

export const COURSE_QUERY_BANNER = 'COURSE_QUERY_BANNER';

export const COURSE_QUERY_LIST = 'COURSE_QUERY_LIST';

export const COURSE_UNPAY = 'COURSE_UNPAY';

export const COURSE_SEARCH_LIST='COURSE_SEARCH_LIST';
